-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-11-08 15:56:08 CST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE matches (
    id            NUMBER NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE,
    turn          CHAR(1) NOT NULL,
    players_id1   NUMBER NOT NULL,
    winner_color  CHAR(1),
    players_id2   NUMBER NOT NULL,
    status        CHAR(1) NOT NULL
);

ALTER TABLE matches ADD CONSTRAINT matches_pk PRIMARY KEY ( id );

CREATE TABLE pieces (
    code     VARCHAR2(3) NOT NULL,
    name     VARCHAR2(20) NOT NULL,
    color    CHAR(1) NOT NULL,
    display  VARCHAR2(3)
);

ALTER TABLE pieces ADD CONSTRAINT pieces_pk PRIMARY KEY ( code );

CREATE TABLE pieces_per_match (
    pieces_code  VARCHAR2(3) NOT NULL,
    matches_id   NUMBER NOT NULL,
    "ROW"        NUMBER NOT NULL,
    "COLUMN"     CHAR(1) NOT NULL,
    color        CHAR(1) NOT NULL
);

ALTER TABLE pieces_per_match ADD CONSTRAINT pieces_per_match_pk PRIMARY KEY ( matches_id,
                                                                              pieces_code );

CREATE TABLE players (
    id              NUMBER NOT NULL,
    name            VARCHAR2(50) NOT NULL,
    username        VARCHAR2(50) NOT NULL,
    played_matches  NUMBER DEFAULT 0 NOT NULL,
    won_matches     NUMBER DEFAULT 0 NOT NULL,
    tied_matches    NUMBER DEFAULT 0 NOT NULL,
    lost_matches    NUMBER DEFAULT 0 NOT NULL
);

ALTER TABLE players ADD CONSTRAINT players_pk PRIMARY KEY ( id );

ALTER TABLE matches
    ADD CONSTRAINT matches_players_fk FOREIGN KEY ( players_id1 )
        REFERENCES players ( id );

ALTER TABLE matches
    ADD CONSTRAINT matches_players_fkv2 FOREIGN KEY ( players_id2 )
        REFERENCES players ( id );

ALTER TABLE pieces_per_match
    ADD CONSTRAINT pieces_per_match_matches_fk FOREIGN KEY ( matches_id )
        REFERENCES matches ( id );

ALTER TABLE pieces_per_match
    ADD CONSTRAINT pieces_per_match_pieces_fk FOREIGN KEY ( pieces_code )
        REFERENCES pieces ( code );

CREATE SEQUENCE matches_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER matches_id_trg BEFORE
    INSERT ON matches
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := matches_id_seq.nextval;
END;
/

CREATE SEQUENCE players_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER players_id_trg BEFORE
    INSERT ON players
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := players_id_seq.nextval;
END;
/

-- INSERT INTO PLAYERS (id, name, username) values (players_id_seq.nextval, 'Kamil', 'kam');
-- INSERT INTO PLAYERS (id, name, username) values (players_id_seq.nextval, 'Andres', 'andrew');


/*

drop table PIECES_PER_MATCH;
drop table PIECES;
drop table MATCHES;
drop table PLAYERS;
drop sequence MATCHES_ID_SEQ;
drop sequence PLAYERS_ID_SEQ;

 */
-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
