/*
Piezas Blancas
*/
-- Rey
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BR', 'Rey Blanco', 1, 'R');
-- Dama
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BD', 'Dama Blanca', 1, 'D');
-- Torres
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BT1', 'Torre Blanca 1', 1, 'T');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BT2', 'Torre Blanca 2', 1, 'T');
-- Caballos
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BC1', 'Caballo Blanco 1', 1, 'C');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BC2', 'Caballo Blanco 2', 1, 'C');
-- Alfiles
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BA1', 'Alfil Blanco 1', 1, 'A');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BA2', 'Alfil Blanco 2', 1, 'A');
-- Peones
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP1', 'Peon Blanco 1', 1, 'P');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP2', 'Peon Blanco 2', 1, 'P');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP3', 'Peon Blanco 3', 1, 'P');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP4', 'Peon Blanco 4', 1, 'P');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP5', 'Peon Blanco 5', 1, 'P');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP6', 'Peon Blanco 6', 1, 'P');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP7', 'Peon Blanco 7', 1, 'P');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('BP8', 'Peon Blanco 8', 1, 'P');

/*
Piezas Negras
*/
-- Rey
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NR', 'Rey Negro', 0, 'r');
-- Dama
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('ND', 'Dama Negra', 0, 'd');
-- Torres
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NT1', 'Torre Negra 1', 0, 't');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NT2', 'Torre Negra 2', 0, 't');
-- Caballos
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NC1', 'Caballo Negro 1', 0, 'c');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NC2', 'Caballo Negro 2', 0, 'c');
-- Alfiles
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NA1', 'Alfil Negro 1', 0, 'a');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NA2', 'Alfil Negro 2', 0, 'a');
-- Peones
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP1', 'Peon Negro 1', 0, 'p');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP2', 'Peon Negro 2', 0, 'p');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP3', 'Peon Negro 3', 0, 'p');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP4', 'Peon Negro 4', 0, 'p');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP5', 'Peon Negro 5', 0, 'p');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP6', 'Peon Negro 6', 0, 'p');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP7', 'Peon Negro 7', 0, 'p');
INSERT INTO PIECES (CODE,NAME,COLOR,DISPLAY) VALUES ('NP8', 'Peon Negro 8', 0, 'p');
COMMIT;