CREATE OR REPLACE TYPE PIECE AS OBJECT(
	CODE VARCHAR2(3),
	DISPLAY VARCHAR2(3),
	CONSTRUCTOR FUNCTION PIECE RETURN SELF AS RESULT
) NOT FINAL;
/

CREATE TYPE BODY PIECE IS
	CONSTRUCTOR FUNCTION PIECE RETURN SELF AS RESULT IS
	BEGIN
		SELF.CODE := '';
		SELF.DISPLAY := '';
		RETURN;
	END;
END;
/