CREATE OR REPLACE TYPE PIECE AS OBJECT(
	CODE VARCHAR2(3),
	DISPLAY VARCHAR2(3),
	COLOR CHAR(1),
	"EXISTS" NUMBER(1),
	CONSTRUCTOR FUNCTION PIECE RETURN SELF AS RESULT
) NOT FINAL;
/

CREATE OR REPLACE TYPE BODY PIECE IS
	CONSTRUCTOR FUNCTION PIECE RETURN SELF AS RESULT IS
	BEGIN
		SELF.CODE := '';
		SELF.DISPLAY := '';
		SELF.COLOR := 0;
		SELF."EXISTS" := 0;
		RETURN;
	END;
END;
/